### ISSUE TITLE
Redirect users to the first page after filtering

### ISSUE THREAD

**Issue by inside1D** [CPSC319-2022/JungleCart#234]
When a user is on the second or the third page, if they filter things with a category, they would still be on these pages although there are no products on this page. 
For instance, here I am on the 3rd page without any filter
 
![image](https://user-images.githubusercontent.com/70651651/231307190-a432ee82-79d8-42c2-acd1-890152187ecb.png)

But if I filter it with the “home and kitchen” category, which only has a few items, I am still on the 3rd page. (Although I can use the arrow to return to earlier pages) 
 
![image](https://user-images.githubusercontent.com/70651651/231307199-f0881248-ce0c-434c-81c5-4136f9a2495d.png)

**Comment by armintalaie** [comment]
implemented
