### ISSUE TITLE
Decide what to do with Analytics of seller dashboard

### ISSUE THREAD

**Issue by inside1D** [CPSC319-2022/JungleCart#237]
The analytics section on the seller dashboard is flashing and is empty, we might need to think about what to do with it.
![image](https://user-images.githubusercontent.com/70651651/231307609-f01b6d15-2829-4965-8a09-ebfbb6b7b24b.png)

**Comment by armintalaie** [comment]
not planning anything at the moment. #272 let's users know. closing this
