### ISSUE TITLE
Add a prompt that tells users the remaining product count when users add too many items 

### ISSUE THREAD

**Issue by inside1D** [CPSC319-2022/JungleCart#247]
Currently the users will get an alert saying "not enough in stock for - test" when they click the checkout button while ordering too many items of the same type. However, since they do not know the remaining number, they have to do "minus -> checkout -> minus -> checkout...." until the item count is within limit. It might be nice to let them know the amount in stock.

**Comment by raphaeldeonova** [comment]
Closed by https://github.com/CPSC319-2022/JungleCart/pull/260
