### ISSUE TITLE
Placing order

### ISSUE THREAD

**Issue by mgbalant** [CPSC319-2022/JungleCart#256]
Can place order without shipping information, but with credit card information and name identity info only (role appears can currently be unassigned). Currently checks for payment info only. Please see screenshot:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/16677006/231643867-d921e523-b066-422f-94ea-f45c7a44b49f.png">

**Comment by armintalaie** [comment]
Has been resolved
