### ISSUE TITLE
Saving user profile details

### ISSUE THREAD

**Issue by mgbalant** [CPSC319-2022/JungleCart#257]
Saves profile details on second try from junglecart.testX@gmail.com accounts (X=1-9), profile details to be saved on first attempt.

**Comment by armintalaie** [comment]
@inside1D  can u verify if it's still like this after deploying. if yes/no update the ticket and the report 
https://github.com/CPSC319-2022/JungleCart/issues/255

**Comment by inside1D** [comment]
@armintalaie  The issue persists. I still cannot modify anything during the first login. I will update the report accordingly
